BOARDCPPSRC = $(BOARD_DIR)/board_configuration.cpp

#Hellen Setup
include $(BOARDS_DIR)/hellen/hellen-common-mega144.mk

#Added features
DDEFS += -DEFI_WS2812=TRUE
#DDEFS += -DEFI_DAC=TRUE
#DDEFS += -DEFI_CDM_INTEGRATION=TRUE
#DDEFS += -DEFI_MC33816=TRUE
DDEFS += -DEFI_POTENTIOMETER=TRUE
#DDEFS += -DBOARD_TLE6240_COUNT=1
#DDEFS += -DBOARD_MC33972_COUNT=1
#DDEFS += -DBOARD_TLE8888_COUNT=1
#DDEFS += -DBOARD_L9779_COUNT=1
#DDEFS += -DBOARD_DRV8860_COUNT=1
#DDEFS += -DBOARD_MC33810_COUNT=1
#DDEFS += -DBOARD_TLE9104_COUNT=1
#DDEFS += -DBOARD_TLE9201_COUNT=1
DDEFS += -DEFI_MAX_31855=TRUE
DDEFS += -DEFI_ONBOARD_MEMS=TRUE
DDEFS += -DEFI_TCU=TRUE
#DDEFS += -DEFI_UART_GPS=TRUE
DDEFS += -DEFI_MALFUNCTION_INDICATOR=TRUE
DDEFS += -DEFI_SENT_SUPPORT=TRUE




