//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on ../../../connectors/custom_firmware.yaml
#pragma once

#define PIN_O1 H144_IGN_1
#define PIN_O2 H144_IGN_2
#define PIN_O3 H144_IGN_3
#define PIN_O4 H144_IGN_4
#define PIN_O5 H144_LS_1
#define PIN_O6 H144_LS_2
#define PIN_O7 H144_LS_3
#define PIN_O8 H144_LS_4
#define PIN_A1 H144_IN_MAP1
#define PIN_A2 H144_IN_MAP2
#define PIN_A3 H144_IN_MAP3
#define PIN_A4 H144_IN_TPS
#define PIN_A5 H144_IN_CLT
#define PIN_A6 H144_IN_VBATT
#define PIN_A7 H144_IN_TPS
#define PIN_A8 H144_IN_IAT
#define PIN_A9 H144_IN_TPS
#define PIN_D1 H144_IN_CRANK
#define PIN_D2 H144_IN_CAM
#define PIN_D3 H144_IN_VSS
#define PIN_D4 H144_IN_D_1
#define PIN_D5 H144_IN_D_2
#define PIN_D6 H144_IN_D_3
#define PIN_D7 H144_IN_D_4
#define PIN_D8 H144_IN_RES1
#define PIN_DA1 H144_IN_AUX1_DIGITAL
#define PIN_DA2 H144_IN_AUX2_DIGITAL
#define PIN_DA3 H144_IN_AUX3_DIGITAL
#define PIN_DA4 H144_IN_AUX4_DIGITAL
#define PIN_DA5 H144_IN_RES2
#define PIN_DA6 H144_IN_RES3
