//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on ../../../connectors/custom_firmware.yaml
#include "pch.h"

// see comments at declaration in pin_repository.h
const char * getBoardSpecificPinName(brain_pin_e brainPin) {
	switch(brainPin) {
		case Gpio::C13: return "IGN1";
		case Gpio::D10: return "INJ4";
		case Gpio::D11: return "INJ3";
		case Gpio::E3: return "IGN4";
		case Gpio::E4: return "IGN3";
		case Gpio::E5: return "IGN2";
		case Gpio::G7: return "INJ1";
		case Gpio::G8: return "INJ2";
		default: return nullptr;
	}
	return nullptr;
}
