//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on ../../../connectors/custom_firmware.yaml
#include "pch.h"

// see comments at declaration in pin_repository.h
const char * getBoardSpecificPinName(brain_pin_e brainPin) {
	switch(brainPin) {
		case Gpio::A6: return "CAM";
		case Gpio::A7: return "AUX3";
		case Gpio::B0: return "AUX1";
		case Gpio::B1: return "CRANK";
		case Gpio::C13: return "IGN1";
		case Gpio::C5: return "AUX4";
		case Gpio::D10: return "INJ4";
		case Gpio::D11: return "INJ3";
		case Gpio::E12: return "D1";
		case Gpio::E13: return "D2";
		case Gpio::E14: return "D3";
		case Gpio::E15: return "D4";
		case Gpio::E3: return "IGN4";
		case Gpio::E4: return "IGN3";
		case Gpio::E5: return "IGN2";
		case Gpio::E9: return "AUX2";
		case Gpio::F10: return "RES2";
		case Gpio::F11: return "VSS";
		case Gpio::F8: return "RES3";
		case Gpio::F9: return "RES1";
		case Gpio::G7: return "INJ1";
		case Gpio::G8: return "INJ2";
		default: return nullptr;
	}
	return nullptr;
}
